[#121] Prepare releng for 3.26.1
eclipse-mylyn/org.eclipse.mylyn pull request #122
Opened 2023-05-06 07:59 UTC by ruspl-afed

Bulk increment to 3.26.1

2023-05-06 08:01 UTC, wimjongman approved these changes
LGTM

2023-05-06 08:10 UTC, BeckerFrank commented on mylyn.github/org.eclipse.mylyn.github.core/META-INF/MANIFEST.MF
> +Require-Bundle: org.eclipse.mylyn.tasks.core;bundle-version="[3.26.1,4.0.0)",
I think we need to change the Bundle-Version to 6.2.1.qualifier for all Mylyn GitHub Artifacts

2023-05-06 08:14 UTC, BeckerFrank requested changes
org.eclipse.mylyn.cdt-feature version should be changed to 5.22.1
and
org.eclipse.mylyn.github.* to 6.2.1

2023-05-06 08:14 UTC, ruspl-afed commented
> org.eclipse.mylyn.cdt-feature version should be changed to 5.22.1 and org.eclipse.mylyn.github.* to 6.2.1

Great catch!

2023-05-06 08:48 UTC, ruspl-afed commented
@BeckerFrank the PR was updated to address your comments

2023-05-06 08:52 UTC, BeckerFrank approved these changes
LGTM

2023-05-06 11:07 UTC, ruspl-afed commented
Let's hold it a bit and try what Ed @merks  is [offering here](https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/123#issuecomment-1537101195)

2023-05-08 09:36 UTC, ruspl-afed commented
> Let's hold it a bit and try what Ed @merks is [offering here](https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/123#issuecomment-1537101195)

Ed @merks are we ready to try version increment facilities? If yes, what do we need to do so?

2023-05-08 09:48 UTC, merks commented
@ruspl-afed 

One thing I would ask and suggest is that we try to produce a milestone build from the main branch **before** you make the version increments in the main branch.

I.e., after this job finishes producing yet another nightly build, do a manual "build with parameters" and choose milestone in the drop-down:

https://ci.eclipse.org/mylyn/job/GitHub-mylyn-Orga/job/org.eclipse.mylyn/job/main/

This way we can test later that publishing another milestone with higher versioned IUs automatically deletes all previous milestone builds for the lower version IUs.  This is essential behavior for keeping the site of the sites limited (like you see how the nightly builds are limited to 5 right now)...

2023-05-08 11:44 UTC, ruspl-afed commented
> One thing I would ask and suggest is that we try to produce a milestone build from the main branch before you make the version increments in the main branch.

Done, https://download.eclipse.org/mylyn/updates/milestone/S202305081049/index.html

2023-05-08 11:51 UTC, wimjongman commented
Nice!!!

2023-05-08 12:19 UTC, merks commented
FYI, now the branding icon is there too.  Note that each simple repository has a link to the commit state of that build:

![image](https://user-images.githubusercontent.com/208716/236821842-d8d2421a-a842-4ea4-910b-0459d24eda87.png)

2023-05-08 15:54 UTC, ruspl-afed commented
Looks perfect, Ed! What is the next step here?

2023-05-08 16:15 UTC, merks commented
I don't know if you folks want to promote the milestone to a release?  I see you already have a release here so maybe that would be confusing?

https://download.eclipse.org/justj/?file=mylyn/drops/3.26.0/v20230503-2157

Of course the content of the repository in this new structure is slightly different, given the name changes as well as the additional feature that was missing.   

One advantage of publishing a release is that then this repository will exist so that downstream consumers could start using that

https://download.eclipse.org/mylyn/updates/release/latest

Note that publishing a release (doing a release build), while it does do a full build, it **does not promote** the results of that build, but rather mirrors the milestone/latest repository as the release repository.

Personally I think this is probably a good idea, but it's your call and and doing this just a matter of doing a build and choosing "release" as the build type...

2023-05-08 19:27 UTC, ruspl-afed commented
I would test the release promotion with a service release 3.26.1
As a very minimum for 3.26.1 we can complete this PR and improve our target regarding 3rd party libs,

2023-05-08 19:40 UTC, merks commented
That’s okay too. You’ll have to increment again afterwards.

2023-05-09 06:56 UTC, merged

2023-05-09 10:16 UTC, merks commented
FYI, you can already see the version updates in the nightly builds:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/717d6f35-7d13-4fb1-9b0e-52ed414d0473)