Improve Mylyn.setup's workingsets task
eclipse-mylyn/org.eclipse.mylyn pull request #142
Opened 2023-05-12 14:43 UTC by merks

Also remove the old API baseline task in favor of the new targlets.based task.

2023-05-12 14:45 UTC, merks commented
@BeckerFrank 

I tried to simplify the working set to use the Repository Predicate which now support a pattern matched against the relative path within the repository.  This avoids problems where the location might look like a regular expression..  I didn't need to exclude anything, but in case you do need that, it's helpful to use an exclusion predicate to exclude the projects in some other working set.

I also got rid of the second set baseline task because you can only really set one...

2023-05-12 14:55 UTC, ruspl-afed approved these changes
LGTM.
Even if I don't understand some magic here.

2023-05-12 14:55 UTC, ruspl-afed commented on org.eclipse.mylyn.releng/oomph/Mylyn.setup
> -    <setupTask
+1

2023-05-12 14:56 UTC, ruspl-afed commented
Let's wait for @BeckerFrank , he is The Master of Mylyn.setup

2023-05-13 10:06 UTC, BeckerFrank commented on org.eclipse.mylyn.releng/oomph/Mylyn.setup
> +      id="mylyn.workingsets"
I think that is the wrong line should this not be in line 212 instead of 150

2023-05-13 10:10 UTC, BeckerFrank requested changes
Please name the correct setup Task as mylyn.workingsets.
The rest is so that we can merge.

2023-05-13 10:11 UTC, merks commented
FYI, note how setting an ID avoids positional references to the task that could be broken by textual editing:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/a3aee53b-c38f-4abf-9121-87155f48e65b)

2023-05-13 10:18 UTC, BeckerFrank commented
> FYI, note how setting an ID avoids positional references to the task that could be broken by textual editing:
> 
> ![image](https://user-images.githubusercontent.com/208716/238128097-a3aee53b-c38f-4abf-9121-87155f48e65b.png)

Thanks I will go and add some more ID's after we have merged this Request.
The ID mylyn.workingsets  for a Resource Creation Task looks wrong for me.

2023-05-13 11:51 UTC, merks commented
Sorry, I thought I force pushed earlier.  Too many irons in the fire.  😢

2023-05-13 12:19 UTC, BeckerFrank approved these changes
LGTM

2023-05-13 12:19 UTC, merged