fix: [#338] enable the action only if we have ProviderManager
eclipse-mylyn/org.eclipse.mylyn pull request #371
Opened 2024-01-20 19:57 UTC by BeckerFrank

2024-01-21 07:49 UTC, merks commented
Does the bundle that sets the system property necessarily start?

2024-01-21 07:50 UTC, ruspl-afed requested changes
Thank you for working on this @BeckerFrank 

1) It is good practice to deliver format changes in a separate PR
2) I believe we can offer better way to implement the fix: involving system properties while working in a context of Eclipse Platform is excessive. Since property tester was already employed why not to implement one.
3) Starting the bundle manually may result in hours of debugging in the future, please avoid this.
and
4) The good fix would be to replace Bugzilla with GitHub, not just disable this action.

2024-01-21 11:08 UTC, BeckerFrank commented
> Thank you for working on this @BeckerFrank
> 
> 1. It is good practice to deliver format changes in a separate PR

I only insert some new lines, the format change was not intended so I do not know how to avoid this.
> 2. I believe we can offer better way to implement the fix: involving system properties while working in a context of Eclipse Platform is excessive. Since property tester was already employed why not to implement one.

Ok, I try to find out how to do this.
> 3. Starting the bundle manually may result in hours of debugging in the future, please avoid this.
>    and
> 4. The good fix would be to replace Bugzilla with GitHub, not just disable this action.

This is an other task, because actual we have not removed the Bugzilla Stuff. I well take a closer look into the GitHub Connector and try to implement this.

2024-01-21 11:34 UTC, ruspl-afed commented
> Ok, I try to find out how to do this.

You can have a look [here](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fexpressions%2FPropertyTester.html) for example

2024-01-23 18:18 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/plugin.xml
> +            description="description for Report Bug Action"
Done with next commit

2024-01-23 18:20 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/plugin.xml
> +                property="org.eclipse.mylyn.tasks.tasks.bugs.propertyTester.showTrim">
Removed with next commit

2024-01-23 18:24 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/plugin.xml
> +                property="org.eclipse.mylyn.tasks.tasks.bugs.propertyTester.showTrim">
provider.any did not work so I use anyProvider with next commit

2024-01-23 18:24 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/plugin.xml
> +	        	    checkEnabled="true">
Yes with next commit

2024-01-23 18:25 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/src/org/eclipse/mylyn/internal/tasks/bugs/ProviderPropertyTester.java
> + * Copyright © 2024 frank
Sorry my fault changed with next commit.

2024-01-23 18:25 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/src/org/eclipse/mylyn/internal/tasks/bugs/ProviderPropertyTester.java
> +public class ProviderPropertyTester extends PropertyTester {
Done with next commit.

2024-01-23 18:25 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/src/org/eclipse/mylyn/internal/tasks/bugs/ProviderPropertyTester.java
> +		// ignore
Good catch, changed with next commit

2024-01-23 18:31 UTC, BeckerFrank commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/src/org/eclipse/mylyn/internal/tasks/bugs/actions/ReportBugHandler.java
> +		SupportProviderManager providerManager = TasksBugsPlugin.getTaskErrorReporter().getProviderManager();
setEnabled is removed in the next commit.

2024-01-24 04:32 UTC, ruspl-afed approved these changes
Thank you for reworking this PR @BeckerFrank  
Added two more comments to consider.

2024-01-24 04:32 UTC, ruspl-afed commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/src/org/eclipse/mylyn/internal/tasks/bugs/TasksBugsPlugin.java
> +		SupportProviderManager providerManager = getTaskErrorReporter().getProviderManager();
With property tester employed we can remove this code.

2024-01-24 04:32 UTC, ruspl-afed commented on mylyn.tasks/org.eclipse.mylyn.tasks.bugs/plugin.xml
> +            description="Report Bug or Enhancement for predefined Products / Projects"
Would be great to i18n this attribute

2024-01-24 09:14 UTC, merks commented
Thanks for working on this and improving the implementation.

2024-01-30 07:39 UTC, ruspl-afed approved these changes
LGTM

2024-01-30 08:09 UTC, merged